
spring:
  application:
    name: springPhoneBook
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/practice
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true


