spring:
  application:
    name: springPhoneBook
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update